[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run prisma:generate"

[deploy]
startCommand = "npm run prisma:migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

