[variables]
NODE_VERSION = "20"

[providers]
node = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "npm run prisma:migrate:deploy && npm start"
